### ISSUE TITLE
arrow physics affecting movement after loading savestate

### ISSUE THREAD

**Issue by ghost** [blitzen-ee/eeo-tas#11]
loading a savestate while inside a gravity arrow causes unwanted movement for the loaded savestate, similar to doing /reset in arrows

steps to replicate:
1. save a state in normal gravity
2. move into a gravity arrow
3. load the savestate and don't move. the smiley will move on its own

**Comment by blitzen-ee** [comment]
Thanks for submitting this issue! I believe the latest version 1.1 has fixed this issues. The fix included adding the Player:queue to the save state. Originally I thought that the tilequeue dealt with the issue.
