### ISSUE TITLE
Player physics is modified when loading state on a dot

### ISSUE THREAD

**Issue by i-am-david-liu** [blitzen-ee/eeo-tas#21]
[Recreate this mini](https://i.imgur.com/Q0CEihg.png)

Procedure:
1. Position smiley on bottom dot. Hold up, notice that it does not reach the one-way
2. Position smiley on bottom dot and do `/state save`, then `/state load`
3. Hold up, notice that now it does
4. Move away from the dots, do `/state save` in an area without any gravity
5. You cannot reach the one-way anymore

**Comment by blitzen-ee** [comment]
This issue is fixed in v1.1.2. I was incorrectly assuming that pop called on the vector would get the first item. I should have been using shift instead (or just index the vector like an array which is what I did). hopefully no more physics problems. As always, thanks for submitting issues.
