### ISSUE TITLE
Deleting collected coins make them reappear when loading state

### ISSUE THREAD

**Issue by i-am-david-liu** [blitzen-ee/eeo-tas#22]
Procedure:
1. Place a coin and collect it
2. Delete the coin
3. Do `/state save` and then `/state load`
4. Notice that the collected coin re-appears.

**Comment by blitzen-ee** [comment]
issue fixed in v1.2 by updating the player gx,gy and bx,by arrays after restoring coins

**Comment by blitzen-ee** [comment]
I closed this on accident. The comment was made for another issue. This issue still exists.
