### ISSUE TITLE
issues with coins and saving/loading states

### ISSUE THREAD

**Issue by ghost** [blitzen-ee/eeo-tas#23]
saving a state while having coins collected and subsequently loading, saving, and loading again creates many duplicate coins. upon reaching millions of coins, saving and loading savestates takes a lot of time

steps to replicate:
1. collect a coin
2. save a savestate
3. load the savestate (optionally multiple times for larger effect). even though they don't appear yet, the coins are saved somewhere
4. save a savestate again
5. load the savestate. the hidden coins suddenly appear
![coin](https://user-images.githubusercontent.com/73705551/124889148-0b91cf80-dfd7-11eb-9f85-dd56b4075079.PNG)

**Comment by blitzen-ee** [comment]
issue fixed in v1.2 by updating the player gx,gy and bx,by arrays after restoring coins
