### ISSUE TITLE
Error message when loading state

### ISSUE THREAD

**Issue by ohc33** [blitzen-ee/eeo-tas#29]
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at UI2/sendChat()
	at MethodInfo-304()

The state seems to load properly but the message appears every time.

**Comment by ohc33** [comment]
Edit: I did not receive an error message this time, but when I loaded state it gave the message "104" in the state loaded popup. It just means the current tick. 
Edit 2: I just crashed when loading state without recording. On Good Egg Galaxy of VG1 campaign but I don't think this is important. Don't see any error, it just abruptly freezes and closes
Steps:
state save 1
move
state load 1
crash

**Comment by blitzen-ee** [comment]
this is fixed in 1.2.1. Instead of displaying the bytearray length (should be same number as ticks), the client now displays which state is being loaded; similar to how it displays when a state is saved.
